### PR TITLE
fix: watch less and sass dependencies

### LINKED ISSUE #1635: Bug：Less 依赖的 watch 问题
## 问题

比如这样的依赖链：

index.tsx > a.less > b.less。

此时，b.less 并没有被 watch，其变更后，并不会触发 a.less 的重新编译，需要手动保存一下 a.less 触发。

### PR DESCRIPTION
**Pull request by YufJi**
close #1635 

**Feature**
- Add a before_rebuild hook to change the update path before the compiler calls update.

---

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:

- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. For large changes, please create an RFC.
- [ ] This message body should clearly illustrate what problems it solves.
- [ ] Ideally, include a test that fails without this PR but passes with it.

### Tests

- [x] Run the tests and other checks with `just ready`

### Edits

- [x] Please ensure that 'Allow edits from maintainers' is checked. PRs without this option may be closed.

### CODE REVIEW

File: packages/mako/src/plugins/less/index.ts [hunk 1]
```diff
@@ -48,24 +57,112 @@ export class LessPlugin {
...
+      }
+    }
+
+    return {
+      content,
+      type: 'css',
+    };
+  };
+
+  beforeRebuild = async (paths: string[]) => {
```
Comment (xusd320) [inline packages/mako/src/plugins/less/index.ts:143]: 看起来会对热更性能有影响，有测试过么？

Comment (xusd320) [reply packages/mako/src/plugins/less/index.ts:143]: 可以尝试排除掉非 less 文件避免插件开销？

Comment (YufJi) [reply packages/mako/src/plugins/less/index.ts:143]: > 可以尝试排除掉非 less 文件避免不必要的插件开销？

那相关逻辑得写在rust层了，hook改一下只处理less变动后的plugin调用，是吧

Comment (xusd320) [reply packages/mako/src/plugins/less/index.ts:143]: > > 可以尝试排除掉非 less 文件避免不必要的插件开销？
> 
> 那相关逻辑得写在rust层了，hook改一下只处理less变动后的plugin调用，是吧

先做 js 里判断，然后直接 return 吧，这样性能影响应该比较小。mako plugin 还没有像 webpack 通用的  module.rules  机制，只为 less 场景做也不太 ok.

Comment (YufJi) [reply packages/mako/src/plugins/less/index.ts:143]: > 可以尝试排除掉非 less 文件避免不必要的插件开销？
加上排查判断，还多了一次查找吧。

image

Comment (xusd320) [reply packages/mako/src/plugins/less/index.ts:143]: 那要不在 rust层先 iter（）.map 一下，让 before_rebuild 的参数是单个 path？

Comment (xusd320) [reply packages/mako/src/plugins/less/index.ts:143]: 感觉也不对，这样会有更多次 ffi 调用，开销更大。要不先 hack 一下，rust层先过滤一遍。顺手帮忙加个 todo 注释，后续再改

**Review by xusd320 — APPROVED** [review]
