### PR TITLE
fix(pack): define value too big to make define not work

### LINKED ISSUE #2388: [Utoopack] define 配置 value 过多会导致 define 失效
### What happened?

举个例子:

```json
{
    "config": {
        "entry": [
            {
                "import": "input/index.ts",
                "name": "main"
            }
        ],
        "define": {
            "RoutePathEnum": "{\"TEST1\":\"TEST1_VALUE\",\"TEST2\":\"TEST2_VALUE\",\"TEST3\":\"TEST3_VALUE\",\"TEST4\":\"TEST4_VALUE\",\"TEST5\":\"TEST5_VALUE\",\"TEST6\":\"TEST6_VALUE\",\"TEST7\":\"TEST7_VALUE\",\"TEST8\":\"TEST8_VALUE\",\"TEST9\":\"TEST9_VALUE\",\"TEST10\":\"TEST10_VALUE\",\"TEST11\":\"TEST11_VALUE\",\"TEST12\":\"TEST12_VALUE\",\"TEST13\":\"TEST13_VALUE\",\"TEST14\":\"TEST14_VALUE\",\"TEST15\":\"TEST15_VALUE\",\"TEST16\":\"TEST16_VALUE\",\"TEST17\":\"TEST17_VALUE\",\"TEST18\":\"TEST18_VALUE\",\"TEST19\":\"TEST19_VALUE\",\"TEST20\":\"TEST20_VALUE\",\"TEST21\":\"TEST21_VALUE\",\"TEST22\":\"TEST22_VALUE\",\"TEST23\":\"TEST23_VALUE\",\"TEST24\":\"TEST24_VALUE\",\"TEST25\":\"TEST25_VALUE\",\"TEST26\":\"TEST26_VALUE\",\"TEST27\":\"TEST27_VALUE\",\"TEST28\":\"TEST28_VALUE\",\"TEST29\":\"TEST29_VALUE\",\"TEST30\":\"TEST30_VALUE\",\"TEST31\":\"TEST31_VALUE\",\"TEST32\":\"TEST32_VALUE\",\"TEST33\":\"TEST33_VALUE\",\"TEST34\":\"TEST34_VALUE\",\"TEST35\":\"TEST35_VALUE\",\"TEST36\":\"TEST36_VALUE\",\"TEST37\":\"TEST37_VALUE\",\"TEST38\":\"TEST38_VALUE\",\"TEST39\":\"TEST39_VALUE\"}"
        }
    }
}
````

下面的 define 大概有 39 组数据，构建产物正常:

Image

如果变成 50 组数据:

```json
"RoutePathEnum": "{\"TEST1\":\"TEST1_VALUE\",\"TEST2\":\"TEST2_VALUE\",\"TEST3\":\"TEST3_VALUE\",\"TEST4\":\"TEST4_VALUE\",\"TEST5\":\"TEST5_VALUE\",\"TEST6\":\"TEST6_VALUE\",\"TEST7\":\"TEST7_VALUE\",\"TEST8\":\"TEST8_VALUE\",\"TEST9\":\"TEST9_VALUE\",\"TEST10\":\"TEST10_VALUE\",\"TEST11\":\"TEST11_VALUE\",\"TEST12\":\"TEST12_VALUE\",\"TEST13\":\"TEST13_VALUE\",\"TEST14\":\"TEST14_VALUE\",\"TEST15\":\"TEST15_VALUE\",\"TEST16\":\"TEST16_VALUE\",\"TEST17\":\"TEST17_VALUE\",\"TEST18\":\"TEST18_VALUE\",\"TEST19\":\"TEST19_VALUE\",\"TEST20\":\"TEST20_VALUE\",\"TEST21\":\"TEST21_VALUE\",\"TEST22\":\"TEST22_VALUE\",\"TEST23\":\"TEST23_VALUE\",\"TEST24\":\"TEST24_VALUE\",\"TEST25\":\"TEST25_VALUE\",\"TEST26\":\"TEST26_VALUE\",\"TEST27\":\"TEST27_VALUE\",\"TEST28\":\"TEST28_VALUE\",\"TEST29\":\"TEST29_VALUE\",\"TEST30\":\"TEST30_VALUE\",\"TEST31\":\"TEST31_VALUE\",\"TEST32\":\"TEST32_VALUE\",\"TEST33\":\"TEST33_VALUE\",\"TEST34\":\"TEST34_VALUE\",\"TEST35\":\"TEST35_VALUE\",\"TEST36\":\"TEST36_VALUE\",\"TEST37\":\"TEST37_VALUE\",\"TEST38\":\"TEST38_VALUE\",\"TEST39\":\"TEST39_VALUE\",\"TEST40\":\"TEST40_VALUE\",\"TEST41\":\"TEST41_VALUE\",\"TEST42\":\"TEST42_VALUE\",\"TEST43\":\"TEST43_VALUE\",\"TEST44\":\"TEST44_VALUE\",\"TEST45\":\"TEST45_VALUE\",\"TEST46\":\"TEST46_VALUE\",\"TEST47\":\"TEST47_VALUE\",\"TEST48\":\"TEST48_VALUE\",\"TEST49\":\"TEST49_VALUE\",\"TEST50\":\"TEST50_VALUE\"}"
```

那 define 替换就会失效:

Image

### Expected result

这里预期行为应该是不失效。

### PR DESCRIPTION
**Pull request by fireairforce**
## Summary

closes: #2388 

上游修复: https://github.com/utooland/next.js/pull/78

## Test Plan

添加了一个很大的测试 case

### CODE REVIEW

File: crates/pack-core/src/client/context.rs [hunk 1]
```diff
@@ -104,21 +104,7 @@ async fn client_defines(define_env: Vc<EnvMap>) -> Result<Vc<CompileTimeDefines>
 
 #[turbo_tasks::function]
 async fn client_free_vars(define_env: Vc<EnvMap>) -> Result<Vc<FreeVarReferences>> {
-    Ok(free_var_references!(
-        ..defines(&*define_env.await?).into_iter() //
-                                                   //FIXME: keep original request when compiling target node
-                                                   //, Buffer = FreeVarReference::EcmaScriptModule {
```
Comment (xusd320) [inline crates/pack-core/src/client/context.rs:110]: 这两个 define 要留着

Comment (fireairforce) [reply crates/pack-core/src/client/context.rs:110]: ok

**Review by elrrrrrrr — DISMISSED** [review]

File: crates/pack-core/src/client/context.rs (hunk 1 above)
Comment (fireairforce) [reply crates/pack-core/src/client/context.rs:110]: done 了
